/** README.md for the data folder, rewritten by the server on every start */
export function workspaceReadme(apiBase: string): string {
  return `# Expense Tracker data folder

This folder is the **source of truth** for the household expense tracker. The
tracker's server is its only regular writer; the app and the API below go
through it. (This README is regenerated by the server; edits here are lost.)

## Changing data: prefer the API

The server's HTTP API is at \`${apiBase}\` (JSON in and out). Every change
made through it is checked, logged with who made it (send an \`X-Actor: <name>\`
header to name yourself), shows up live in every open app, and the
app's Data page can undo it.

Read:
- \`GET  /summary\` — counts, date range, uncategorised count, per-account coverage
- \`GET  /categories\` — every category: id, full path, oneOff/archived flags, usage
- \`GET  /transactions?uncategorized=1&q=&account=&from=&to=&category=&limit=&offset=\`
- \`GET  /rules\`, \`GET /suggestions\` (rule candidates mined from the data)
- \`GET  /files/transactions.csv\` (and the other files) — raw text
- \`GET  /activity\` — recent changes and who made them

Write:
- \`POST /import\` \`{"csv": "<bank export text>", "account": "ANZ Visa", "dryRun": true}\` —
  same pipeline as the app's import dialog: column/date/sign detection, saved
  bank profiles (\`"profile": "<name>"\`, or matched by column layout),
  duplicate skipping, rules. Run with \`dryRun\` first and check \`settings\`,
  \`range\`, \`sample\` and \`warnings\`; then repeat without it.
- \`POST /transactions/categorize\` \`{"items": [{"id": "…", "category": "Groceries"}]}\` —
  \`category\` may be an id, a full path (\`Travel > Japan 2026 > Food\`) or a
  unique name; optional \`notes\`
- \`POST /categories\` \`{"path": "Travel > Japan 2027 > Food", "oneOff": true}\` — creates missing levels
- \`POST /rules\` \`{"pattern": "WOOLWORTHS", "category": "Groceries"}\` — also files matching
  uncategorised transactions unless \`"apply": false\`
- \`POST /rules/apply\` — run every rule over the uncategorised pile
- \`POST /transactions\` \`{"transactions": [{"date": "2026-10-01", "description": "…", "amount": 12.5}]}\` — manual entries

## Editing the files directly

Also fine (bulk edits with a script, a spreadsheet). The server notices within
seconds, snapshots the previous version (at most hourly), logs the change as a
direct file edit and pushes it to every open app. Rules for direct edits:
- Never change \`ID\` / \`Id\` values; transactions and rules reference them.
- Keep the header row. A transactions.csv the server can't parse is left alone
  and the app refuses to build on it until it's fixed.
- Write the whole file in one go (write a temp file, then rename it over).
- Edits through the app or API in the meantime are not merged into your
  copy: read, change and write back quickly, or use the API.

## Files

### categories.csv — the category tree
\`\`\`
Id,ParentId,Name,Path,OneOff,Archived,Color,Budget,Notes,CreatedAt
\`\`\`
One row per node; arbitrary nesting via \`ParentId\` (empty = top-level).
Transactions may be filed on **any** node, not just leaves; reports roll
descendants up into ancestors.
- \`Id\` — stable readable slug (e.g. \`travel-mex26\`). **Never change it.**
- \`ParentId\` — the parent node's Id, empty for a top-level node (a chart bucket).
- \`Name\` — display name; unique among siblings only. Must not contain \`>\`.
- \`Path\` — **derived** (e.g. \`Travel > Mexico 2026 > Flights\`), rewritten from
  ParentId/Name; leave it blank when adding rows. Editing Path alone changes nothing.
- \`OneOff\` — \`true\` marks a one-off cost centre ("project": a trip, a
  renovation…). Its subtree clusters at the end of pickers and can be
  excluded from trend charts.
- \`Archived\` — \`true\` retires the node's whole subtree: hidden from pickers
  and suggestions, its rules disabled, history kept. **Don't categorise new
  spending into an archived subtree.**
- \`Color\`, \`Budget\`, \`Notes\`, \`CreatedAt\` — optional metadata.
The top-level node \`uncategorized\` ("Uncategorized") is special: rows needing
triage are filed there, and the server re-creates it if it's missing.

### transactions.csv — every transaction
\`\`\`
ID,Date,Description,Amount,CategoryId,Account,Notes,OriginalAmount,FxRate
\`\`\`
- \`ID\` — stable unique row id. **Never change it**. New rows: any unique string.
- \`Date\` — ISO \`yyyy-mm-dd\`
- \`Amount\` — plain number, 2 decimals, **always AUD**. **Positive = expense, negative = income/refund.**
- \`CategoryId\` — the Id of a categories.csv node (any level); \`uncategorized\`
  for rows needing triage. An unknown CategoryId is auto-registered as a
  top-level node named after the id (fix it in categories.csv if that happens).
- \`Account\` — source account label (e.g. "ANZ Visa")
- \`Notes\` — optional free text
- \`OriginalAmount\`, \`FxRate\` — only for foreign-currency imports: the
  source-currency amount and the rate used (\`Amount ≈ OriginalAmount × FxRate\`).
  Duplicate detection matches on \`OriginalAmount\` when present.

### rules.csv — auto-categorisation rules
\`\`\`
Pattern,IsRegex,CategoryId,Enabled,CreatedAt
\`\`\`
"Description contains Pattern (case-insensitive; regex if IsRegex) → file it
under CategoryId." Row order is priority: the first matching rule wins.

### import-profiles.json — saved bank CSV column mappings (app-managed)

## Other contents

- \`activity.jsonl\` — the change log (one JSON object per line; a later line
  with the same id supersedes an earlier one)
- \`backups/<stamp>-<reason>/\` — snapshots of the four data files: before each
  day's first change, before imports/restores/uploads, before applying a
  direct file edit (at most hourly), and on demand. Kept for 30 days, then the
  newest of each month. Restore from the app's Data page, or copy the files back.
`;
}
